fun main() {
    println("Dec 1a: ${Dec1.a()}")
    println("Dec 1b: ${Dec1.b()}")
    println("Dec 2a: ${Dec2.a()}")
    println("Dec 2b: ${Dec2.b()}")
    println("Dec 3a: ${Dec3.a()}")
    println("Dec 3b: ${Dec3.b()}")
    println("Dec 4a: ${Dec4.a()}")
    println("Dec 4b: ${Dec4.b()}")
    println("Dec 5a: ${Dec5.a()}")
    println("Dec 5b: ${Dec5.b()}")
    println("Dec 6a: ${Dec6.a()}")
    println("Dec 6b: ${Dec6.b()}")
    println("Dec 7a: ${Dec7.a()}")
    println("Dec 7b: ${Dec7.b()}")
    println("Dec 8a: ${Dec8.a()}")
    println("Dec 8b: ${Dec8.b()}")
    println("Dec 9a: ${Dec9.a()}")
    println("Dec 9b: ${Dec9.b()}")
    println("Dec 10a: ${Dec10.a()}")
    println("Dec 10b:\n${Dec10.b()}")
    println("Dec 11a: ${Dec11.a()}")
    println("Dec 11b: ${Dec11.b()}")
    println("Dec 12a: ${Dec12.a()}")
    println("Dec 12b: ${Dec12.b()}")
//    println("Dec 13a: ${Dec13.a()}")
//    println("Dec 13b: ${Dec13.b()}")
    println("Dec 14a: ${Dec14.a()}")
    println("Dec 14b: ${Dec14.b()}")
//    println("Dec 15a: ${Dec15.a()}")
//    println("Dec 15b: ${Dec15.b()}")
//    println("Dec 16a: ${Dec16.a()}")
//    println("Dec 16b: ${Dec16.b()}")
//    println("Dec 17a: ${Dec17.a()}")
//    println("Dec 17b: ${Dec17.b()}")
    println("Dec 18a: ${Dec18.a()}")
    println("Dec 18b: ${Dec18.b()}")
    println("Dec 19a: ${Dec19.a()}")
    println("Dec 19b: ${Dec19.b()}")
    println("Dec 20a: ${Dec20.a()}")
    println("Dec 20b: ${Dec20.b()}")
    println("Dec 21a: ${Dec21.a()}")
    println("Dec 21b: ${Dec21b.b()}")
//    println("Dec 22a: ${Dec22.a()}")
//    println("Dec 22b: ${Dec22.b()}")
//    println("Dec 23a: ${Dec23.a()}")
//    println("Dec 23b: ${Dec23.b()}")
//    println("Dec 24a: ${Dec24.a()}")
//    println("Dec 24b: ${Dec24.b()}")
    println("Dec 25a: ${Dec25.a()}")
}
