fun main() {
//    println("Dec 1a: ${Dec1.a()}")
//    println("Dec 1b: ${Dec1.b()}")
//    println("Dec 2a: ${Dec2.a()}")
//    println("Dec 2b: ${Dec2.b()}")
//    println("Dec 3a: ${Dec3.a()}")
//    println("Dec 3b: ${Dec3.b()}")
//    println("Dec 4a: ${Dec4.a()}")
//    println("Dec 4b: ${Dec4.b()}")
//    println("Dec 5a: ${Dec5.a()}")
//    println("Dec 5b: ${Dec5.b()}")
//    println("Dec 6a: ${Dec6.a()}")
//    println("Dec 6b: ${Dec6.b()}")
//    println("Dec 7a: ${Dec7.a()}")
//    println("Dec 7b: ${Dec7.b()}")
//    println("Dec 8a: ${Dec8.a()}")
//    println("Dec 8b: ${Dec8.b()}")
//    println("Dec 10a: ${Dec10.a()}")
//    println("Dec 10b:\n${Dec10.b()}")
//    println("Dec 11a: ${Dec11.a()}")
//    println("Dec 11b: ${Dec11.b()}")
//    println("Dec 12a: ${Dec12.a()}")
//    println("Dec 12b: ${Dec12.b()}")
    println("Dec 18a: ${Dec18.a()}")
    println("Dec 19a: ${Dec19.a()}")
}
